"""remove online flag key from user

Revision ID: 0451cbf20ebe
Revises: 6dad3433e3c5
Create Date: 2026-04-03 18:41:38.988071

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0451cbf20ebe'
down_revision: Union[str, Sequence[str], None] = '6dad3433e3c5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'is_online')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('is_online', sa.BOOLEAN(), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
