"""add user authenticators table

Revision ID: 2a3126e659c1
Revises: 4cb51ff157c9
Create Date: 2026-04-20 14:41:49.111195

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '2a3126e659c1'
down_revision: Union[str, Sequence[str], None] = '4cb51ff157c9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user_authenticators',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('credential_id', sa.Text(), nullable=False),
    sa.Column('public_key', sa.Text(), nullable=False),
    sa.Column('sign_count', sa.Integer(), nullable=True),
    sa.Column('transports', sa.Text(), nullable=True),
    sa.Column('encrypted_dek_prf', sa.Text(), nullable=True),
    sa.Column('dek_iv_prf', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_user_authenticators_credential_id'), 'user_authenticators', ['credential_id'], unique=True)
    op.create_index(op.f('ix_user_authenticators_id'), 'user_authenticators', ['id'], unique=False)
    op.drop_index(op.f('ix_garage_user_id'), table_name='garage_user')
    op.drop_index(op.f('ix_garage_user_username'), table_name='garage_user')
    op.drop_table('garage_user')
    op.drop_index(op.f('ix_work_entries_id'), table_name='work_entries')
    op.drop_table('work_entries')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('work_entries',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.Column('title', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('vehicle_type', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('work_type', sa.VARCHAR(), server_default=sa.text("'TECHNICAL'::character varying"), autoincrement=False, nullable=False),
    sa.Column('description', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('image_before', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('image_after', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('work_entries_pkey'))
    )
    op.create_index(op.f('ix_work_entries_id'), 'work_entries', ['id'], unique=False)
    op.create_table('garage_user',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('username', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('password_hash', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('garage_user_pkey'))
    )
    op.create_index(op.f('ix_garage_user_username'), 'garage_user', ['username'], unique=True)
    op.create_index(op.f('ix_garage_user_id'), 'garage_user', ['id'], unique=False)
    op.drop_index(op.f('ix_user_authenticators_id'), table_name='user_authenticators')
    op.drop_index(op.f('ix_user_authenticators_credential_id'), table_name='user_authenticators')
    op.drop_table('user_authenticators')
    # ### end Alembic commands ###
