"""Convert 3 layer encryption

Revision ID: 3b3f6fec9a51
Revises: 1071bd3ac250
Create Date: 2026-03-25 11:44:54.508893

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3b3f6fec9a51'
down_revision: Union[str, Sequence[str], None] = '1071bd3ac250'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('encrypted_dek', sa.Text(), nullable=True))
    op.add_column('users', sa.Column('dek_iv', sa.String(), nullable=True))
    op.add_column('users', sa.Column('priv_key_iv', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'priv_key_iv')
    op.drop_column('users', 'dek_iv')
    op.drop_column('users', 'encrypted_dek')
    # ### end Alembic commands ###
