"""add socket_sid

Revision ID: 751be46066f3
Revises: 8c624254e1f9
Create Date: 2026-03-26 10:26:29.839209

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '751be46066f3'
down_revision: Union[str, Sequence[str], None] = '8c624254e1f9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('socket_sid', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'socket_sid')
    # ### end Alembic commands ###
