"""calling logs models

Revision ID: 97d07d0409c5
Revises: 0451cbf20ebe
Create Date: 2026-04-07 17:49:29.442638

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '97d07d0409c5'
down_revision: Union[str, Sequence[str], None] = '0451cbf20ebe'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('call_logs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('initiator_id', sa.Integer(), nullable=False),
    sa.Column('receiver_id', sa.Integer(), nullable=False),
    sa.Column('started_by_id', sa.Integer(), nullable=False),
    sa.Column('accepted_by_id', sa.Integer(), nullable=True),
    sa.Column('ended_by_id', sa.Integer(), nullable=True),
    sa.Column('call_type', sa.String(), nullable=False),
    sa.Column('final_call_type', sa.String(), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('started_at', sa.DateTime(), nullable=True),
    sa.Column('answered_at', sa.DateTime(), nullable=True),
    sa.Column('ended_at', sa.DateTime(), nullable=True),
    sa.Column('duration_seconds', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['accepted_by_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['ended_by_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['initiator_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['receiver_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['started_by_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_call_logs_id'), 'call_logs', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_call_logs_id'), table_name='call_logs')
    op.drop_table('call_logs')
    # ### end Alembic commands ###
