"""Add message edit/delete and chat clear features

Revision ID: a92ac73d4d4b
Revises: c989c83e51f8
Create Date: 2026-03-23 16:11:43.030240

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a92ac73d4d4b'
down_revision: Union[str, Sequence[str], None] = 'c989c83e51f8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('chat_clears',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('contact_id', sa.Integer(), nullable=False),
    sa.Column('cleared_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['contact_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_chat_clears_id'), 'chat_clears', ['id'], unique=False)
    op.add_column('messages', sa.Column('is_deleted', sa.Boolean(), nullable=True))
    op.add_column('messages', sa.Column('is_edited', sa.Boolean(), nullable=True))
    op.add_column('messages', sa.Column('edited_at', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('messages', 'edited_at')
    op.drop_column('messages', 'is_edited')
    op.drop_column('messages', 'is_deleted')
    op.drop_index(op.f('ix_chat_clears_id'), table_name='chat_clears')
    op.drop_table('chat_clears')
    # ### end Alembic commands ###
