"""Add private key wrapping

Revision ID: c989c83e51f8
Revises: 3c93cc98117d
Create Date: 2026-03-23 10:59:33.038202

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c989c83e51f8'
down_revision: Union[str, Sequence[str], None] = '3c93cc98117d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('encrypted_private_key', sa.Text(), nullable=True))
    op.add_column('users', sa.Column('keys_salt', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'keys_salt')
    op.drop_column('users', 'encrypted_private_key')
    # ### end Alembic commands ###
